### ISSUE TITLE
支持5.15和6.1

### ISSUE THREAD

**Issue by JiuGeFaCai** [TapetalArray/GKI-Custom#1]
麻烦问一下支持5.15和6.1吗？谢谢

**Comment by TapetalArray** [comment]
> 麻烦问一下支持5.15和6.1吗？谢谢

没问题。。。

**Comment by JiuGeFaCai** [comment]
> > 麻烦问一下支持5.15和6.1吗？谢谢
> 
> 没问题。。。

直接用是吧?

**Comment by TapetalArray** [comment]
> > > 麻烦问一下支持5.15和6.1吗？谢谢
> > 
> > 
> > 没问题。。。
> 
> 直接用是吧?

我没有5.15和6.1的设备，也没有测试过，这些补丁应该是可以用在5.15和6.1的，只是defconfig应该需要改改，我也没有测试过

**Comment by JiuGeFaCai** [comment]
> > > > 麻烦问一下支持5.15和6.1吗？谢谢
> > > 
> > > 
> > > 没问题。。。
> > 
> > 
> > 直接用是吧?
> 
> 我没有5.15和6.1的设备，也没有测试过，这些补丁应该是可以用在5.15和6.1的，只是defconfig应该需要改改，我也没有测试过

ok,行吧，谢谢了
